- Environments:
  - CartPole-v1:
    - skeleton: [[4], 2, [32, elu], [32, elu]]
    - heurestics:
      - egreedy_cp: Random
      - theta_omega: Great
      - hybrid: Hybrid
      - badhr: Bad
    - schedulers:
      - LinearDecay: [800, 50]
      - DampedOscillator: [800, 50, 50, 0.1, DO1]
      - DampedOscillator: [800, 100, 100, 0.1, DO2]
      - DampedOscillator: [1200, 50, 50, 0.1, DO1_Ext]
    - ts-tutoring: True
    - ts-heurestics:
      - egreedy_cp: Random
      - theta_omega: Great
    - ts-schedulers:
      - LinearDecay: [800, 50]
      - DampedOscillator: [800, 50, 50, 0.1, DO1]
      - DampedOscillator: [800, 100, 100, 0.1, DO2]
      - DampedOscillator: [1200, 50, 50, 0.1, DO1_Ext]
    - trials: 10
    - episodes: 1500
    - steps: 500
  - MountainCar-v0:
    - skeleton: [[2], 3, [32, elu], [32, elu]]
    - heurestics:
      - egreedy_mc: Random
      - mc_great: Great
    - schedulers:
      - LinearDecay: [800, 50]
      - DampedOscillator: [800, 50, 50, 0.1, DO1]
      - DampedOscillator: [800, 100, 100, 0.1, DO2]
      - DampedOscillator: [1200, 50, 50, 0.1, DO1_Ext]
    - ts-tutoring: True
    - ts-heurestics:
      - egreedy_mc: Random
      - mc_great: Great
    - ts-schedulers:
      - LinearDecay: [800, 50]
      - DampedOscillator: [800, 50, 50, 0.1, DO1]
      - DampedOscillator: [800, 100, 100, 0.1, DO2]
      - DampedOscillator: [1200, 50, 50, 0.1, DO1_Ext]
    - trials: 10
    - episodes: 1500
    - steps: 200
